/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    PaymentMethodDTO,
    PaymentMethodDTOFromJSON,
    PaymentMethodDTOToJSON,
    PaymentMethodDraftDTO,
    PaymentMethodDraftDTOFromJSON,
    PaymentMethodDraftDTOToJSON,
} from '../models';

export interface CreatePaymentMethodRequest {
    paymentMethodDraftDTO: PaymentMethodDraftDTO;
}

export interface DeletePaymentMethodByIdRequest {
    id: string;
}

export interface FilterPaymentMethodsRequest {
    filter: string;
    sort: string;
    expand: string;
    project: string;
    limit?: number;
    offset?: number;
}

export interface FindPaymentMethodByIdRequest {
    id: string;
}

export interface UpdatePaymentMethodByIdRequest {
    id: string;
    paymentMethodDraftDTO: PaymentMethodDraftDTO;
}

/**
 * 
 */
export class PaymentMethodsApi extends runtime.BaseAPI {

    /**
     * Creates a new payment method.
     */
    async createPaymentMethodRaw(requestParameters: CreatePaymentMethodRequest): Promise<runtime.ApiResponse<PaymentMethodDTO>> {
        if (requestParameters.paymentMethodDraftDTO === null || requestParameters.paymentMethodDraftDTO === undefined) {
            throw new runtime.RequiredError('paymentMethodDraftDTO','Required parameter requestParameters.paymentMethodDraftDTO was null or undefined when calling createPaymentMethod.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/config/payment-methods`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentMethodDraftDTOToJSON(requestParameters.paymentMethodDraftDTO),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentMethodDTOFromJSON(jsonValue));
    }

    /**
     * Creates a new payment method.
     */
    async createPaymentMethod(requestParameters: CreatePaymentMethodRequest): Promise<PaymentMethodDTO> {
        const response = await this.createPaymentMethodRaw(requestParameters);
        return await response.value();
    }

    /**
     * Deletes a payment method by id.
     */
    async deletePaymentMethodByIdRaw(requestParameters: DeletePaymentMethodByIdRequest): Promise<runtime.ApiResponse<PaymentMethodDTO>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deletePaymentMethodById.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/config/payment-methods/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentMethodDTOFromJSON(jsonValue));
    }

    /**
     * Deletes a payment method by id.
     */
    async deletePaymentMethodById(requestParameters: DeletePaymentMethodByIdRequest): Promise<PaymentMethodDTO> {
        const response = await this.deletePaymentMethodByIdRaw(requestParameters);
        return await response.value();
    }

    /**
     * Lists all payment methods.
     */
    async filterPaymentMethodsRaw(requestParameters: FilterPaymentMethodsRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.filter === null || requestParameters.filter === undefined) {
            throw new runtime.RequiredError('filter','Required parameter requestParameters.filter was null or undefined when calling filterPaymentMethods.');
        }

        if (requestParameters.sort === null || requestParameters.sort === undefined) {
            throw new runtime.RequiredError('sort','Required parameter requestParameters.sort was null or undefined when calling filterPaymentMethods.');
        }

        if (requestParameters.expand === null || requestParameters.expand === undefined) {
            throw new runtime.RequiredError('expand','Required parameter requestParameters.expand was null or undefined when calling filterPaymentMethods.');
        }

        if (requestParameters.project === null || requestParameters.project === undefined) {
            throw new runtime.RequiredError('project','Required parameter requestParameters.project was null or undefined when calling filterPaymentMethods.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.filter !== undefined) {
            queryParameters['filter'] = requestParameters.filter;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        if (requestParameters.expand !== undefined) {
            queryParameters['expand'] = requestParameters.expand;
        }

        if (requestParameters.project !== undefined) {
            queryParameters['project'] = requestParameters.project;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/config/payment-methods`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Lists all payment methods.
     */
    async filterPaymentMethods(requestParameters: FilterPaymentMethodsRequest): Promise<void> {
        await this.filterPaymentMethodsRaw(requestParameters);
    }

    /**
     * Returns a payment method by id.
     */
    async findPaymentMethodByIdRaw(requestParameters: FindPaymentMethodByIdRequest): Promise<runtime.ApiResponse<PaymentMethodDTO>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findPaymentMethodById.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/config/payment-methods/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentMethodDTOFromJSON(jsonValue));
    }

    /**
     * Returns a payment method by id.
     */
    async findPaymentMethodById(requestParameters: FindPaymentMethodByIdRequest): Promise<PaymentMethodDTO> {
        const response = await this.findPaymentMethodByIdRaw(requestParameters);
        return await response.value();
    }

    /**
     * Updates a payment method by id.
     */
    async updatePaymentMethodByIdRaw(requestParameters: UpdatePaymentMethodByIdRequest): Promise<runtime.ApiResponse<PaymentMethodDTO>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updatePaymentMethodById.');
        }

        if (requestParameters.paymentMethodDraftDTO === null || requestParameters.paymentMethodDraftDTO === undefined) {
            throw new runtime.RequiredError('paymentMethodDraftDTO','Required parameter requestParameters.paymentMethodDraftDTO was null or undefined when calling updatePaymentMethodById.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/config/payment-methods/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentMethodDraftDTOToJSON(requestParameters.paymentMethodDraftDTO),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentMethodDTOFromJSON(jsonValue));
    }

    /**
     * Updates a payment method by id.
     */
    async updatePaymentMethodById(requestParameters: UpdatePaymentMethodByIdRequest): Promise<PaymentMethodDTO> {
        const response = await this.updatePaymentMethodByIdRaw(requestParameters);
        return await response.value();
    }

}
