/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ValueTypeDTO,
    ValueTypeDTOFromJSON,
    ValueTypeDTOToJSON,
    ValueTypeDraftDTO,
    ValueTypeDraftDTOFromJSON,
    ValueTypeDraftDTOToJSON,
} from '../models';

export interface CreateValueTypeRequest {
    valueTypeDraftDTO: ValueTypeDraftDTO;
}

export interface DeleteValueTypeByIdRequest {
    id: string;
}

export interface FilterValueTypesRequest {
    filter: string;
    sort: string;
    expand: string;
    project: string;
    limit?: number;
    offset?: number;
}

export interface UpdateValueTypeRequest {
    id: string;
    valueTypeDraftDTO: ValueTypeDraftDTO;
}

/**
 * 
 */
export class ValueTypesApi extends runtime.BaseAPI {

    /**
     * Creates new record
     */
    async createValueTypeRaw(requestParameters: CreateValueTypeRequest): Promise<runtime.ApiResponse<ValueTypeDTO>> {
        if (requestParameters.valueTypeDraftDTO === null || requestParameters.valueTypeDraftDTO === undefined) {
            throw new runtime.RequiredError('valueTypeDraftDTO','Required parameter requestParameters.valueTypeDraftDTO was null or undefined when calling createValueType.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cms/value-types`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ValueTypeDraftDTOToJSON(requestParameters.valueTypeDraftDTO),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ValueTypeDTOFromJSON(jsonValue));
    }

    /**
     * Creates new record
     */
    async createValueType(requestParameters: CreateValueTypeRequest): Promise<ValueTypeDTO> {
        const response = await this.createValueTypeRaw(requestParameters);
        return await response.value();
    }

    /**
     * Deletes a record by id
     */
    async deleteValueTypeByIdRaw(requestParameters: DeleteValueTypeByIdRequest): Promise<runtime.ApiResponse<ValueTypeDTO>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteValueTypeById.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/cms/value-types/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ValueTypeDTOFromJSON(jsonValue));
    }

    /**
     * Deletes a record by id
     */
    async deleteValueTypeById(requestParameters: DeleteValueTypeByIdRequest): Promise<ValueTypeDTO> {
        const response = await this.deleteValueTypeByIdRaw(requestParameters);
        return await response.value();
    }

    /**
     * Filters the collection
     */
    async filterValueTypesRaw(requestParameters: FilterValueTypesRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.filter === null || requestParameters.filter === undefined) {
            throw new runtime.RequiredError('filter','Required parameter requestParameters.filter was null or undefined when calling filterValueTypes.');
        }

        if (requestParameters.sort === null || requestParameters.sort === undefined) {
            throw new runtime.RequiredError('sort','Required parameter requestParameters.sort was null or undefined when calling filterValueTypes.');
        }

        if (requestParameters.expand === null || requestParameters.expand === undefined) {
            throw new runtime.RequiredError('expand','Required parameter requestParameters.expand was null or undefined when calling filterValueTypes.');
        }

        if (requestParameters.project === null || requestParameters.project === undefined) {
            throw new runtime.RequiredError('project','Required parameter requestParameters.project was null or undefined when calling filterValueTypes.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.filter !== undefined) {
            queryParameters['filter'] = requestParameters.filter;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        if (requestParameters.expand !== undefined) {
            queryParameters['expand'] = requestParameters.expand;
        }

        if (requestParameters.project !== undefined) {
            queryParameters['project'] = requestParameters.project;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/cms/value-types`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Filters the collection
     */
    async filterValueTypes(requestParameters: FilterValueTypesRequest): Promise<void> {
        await this.filterValueTypesRaw(requestParameters);
    }

    /**
     * Updates a record
     */
    async updateValueTypeRaw(requestParameters: UpdateValueTypeRequest): Promise<runtime.ApiResponse<ValueTypeDTO>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateValueType.');
        }

        if (requestParameters.valueTypeDraftDTO === null || requestParameters.valueTypeDraftDTO === undefined) {
            throw new runtime.RequiredError('valueTypeDraftDTO','Required parameter requestParameters.valueTypeDraftDTO was null or undefined when calling updateValueType.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cms/value-types/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ValueTypeDraftDTOToJSON(requestParameters.valueTypeDraftDTO),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ValueTypeDTOFromJSON(jsonValue));
    }

    /**
     * Updates a record
     */
    async updateValueType(requestParameters: UpdateValueTypeRequest): Promise<ValueTypeDTO> {
        const response = await this.updateValueTypeRaw(requestParameters);
        return await response.value();
    }

}
