/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AddressVerifiedDTO,
    AddressVerifiedDTOFromJSON,
    AddressVerifiedDTOFromJSONTyped,
    AddressVerifiedDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface AddressDTO
 */
export interface AddressDTO {
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof AddressDTO
     */
    createdAt?: number;
    /**
     * 
     * @type {number}
     * @memberof AddressDTO
     */
    updatedAt?: number;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    countryCode: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    region?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    quarter?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    streetName?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    streetNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    building?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    entrance?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    floor?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    apartment?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    companyName?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    companyId?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    vatId?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    additionalStreetInfo?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    additionalAddressInfo?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AddressDTO
     */
    isDefaultBillingAddress: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AddressDTO
     */
    isDefaultShippingAddress: boolean;
    /**
     * 
     * @type {AddressVerifiedDTO}
     * @memberof AddressDTO
     */
    verified: AddressVerifiedDTO;
    /**
     * 
     * @type {object}
     * @memberof AddressDTO
     */
    custom?: object;
}

export function AddressDTOFromJSON(json: any): AddressDTO {
    return AddressDTOFromJSONTyped(json, false);
}

export function AddressDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'email': json['email'],
        'phoneNumber': json['phoneNumber'],
        'countryCode': json['countryCode'],
        'region': !exists(json, 'region') ? undefined : json['region'],
        'city': json['city'],
        'quarter': !exists(json, 'quarter') ? undefined : json['quarter'],
        'streetName': !exists(json, 'streetName') ? undefined : json['streetName'],
        'streetNumber': !exists(json, 'streetNumber') ? undefined : json['streetNumber'],
        'postalCode': !exists(json, 'postalCode') ? undefined : json['postalCode'],
        'building': !exists(json, 'building') ? undefined : json['building'],
        'entrance': !exists(json, 'entrance') ? undefined : json['entrance'],
        'floor': !exists(json, 'floor') ? undefined : json['floor'],
        'apartment': !exists(json, 'apartment') ? undefined : json['apartment'],
        'companyName': !exists(json, 'companyName') ? undefined : json['companyName'],
        'companyId': !exists(json, 'companyId') ? undefined : json['companyId'],
        'vatId': !exists(json, 'vatId') ? undefined : json['vatId'],
        'additionalStreetInfo': !exists(json, 'additionalStreetInfo') ? undefined : json['additionalStreetInfo'],
        'additionalAddressInfo': !exists(json, 'additionalAddressInfo') ? undefined : json['additionalAddressInfo'],
        'isDefaultBillingAddress': json['isDefaultBillingAddress'],
        'isDefaultShippingAddress': json['isDefaultShippingAddress'],
        'verified': AddressVerifiedDTOFromJSON(json['verified']),
        'custom': !exists(json, 'custom') ? undefined : json['custom'],
    };
}

export function AddressDTOToJSON(value?: AddressDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'email': value.email,
        'phoneNumber': value.phoneNumber,
        'countryCode': value.countryCode,
        'region': value.region,
        'city': value.city,
        'quarter': value.quarter,
        'streetName': value.streetName,
        'streetNumber': value.streetNumber,
        'postalCode': value.postalCode,
        'building': value.building,
        'entrance': value.entrance,
        'floor': value.floor,
        'apartment': value.apartment,
        'companyName': value.companyName,
        'companyId': value.companyId,
        'vatId': value.vatId,
        'additionalStreetInfo': value.additionalStreetInfo,
        'additionalAddressInfo': value.additionalAddressInfo,
        'isDefaultBillingAddress': value.isDefaultBillingAddress,
        'isDefaultShippingAddress': value.isDefaultShippingAddress,
        'verified': AddressVerifiedDTOToJSON(value.verified),
        'custom': value.custom,
    };
}


