/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CartDiscountTargetDTO,
    CartDiscountTargetDTOFromJSON,
    CartDiscountTargetDTOFromJSONTyped,
    CartDiscountTargetDTOToJSON,
    CartDiscountValueDTO,
    CartDiscountValueDTOFromJSON,
    CartDiscountValueDTOFromJSONTyped,
    CartDiscountValueDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface CartDiscountDraftDTO
 */
export interface CartDiscountDraftDTO {
    /**
     * 
     * @type {string}
     * @memberof CartDiscountDraftDTO
     */
    authority: CartDiscountDraftDTOAuthorityEnum;
    /**
     * 
     * @type {string}
     * @memberof CartDiscountDraftDTO
     */
    merchantKey?: string;
    /**
     * 
     * @type {object}
     * @memberof CartDiscountDraftDTO
     */
    name: object;
    /**
     * 
     * @type {object}
     * @memberof CartDiscountDraftDTO
     */
    description?: object;
    /**
     * 
     * @type {CartDiscountValueDTO}
     * @memberof CartDiscountDraftDTO
     */
    value: CartDiscountValueDTO;
    /**
     * 
     * @type {string}
     * @memberof CartDiscountDraftDTO
     */
    cartPredicate: string;
    /**
     * 
     * @type {CartDiscountTargetDTO}
     * @memberof CartDiscountDraftDTO
     */
    target?: CartDiscountTargetDTO;
    /**
     * 
     * @type {number}
     * @memberof CartDiscountDraftDTO
     */
    sortOrder: number;
    /**
     * 
     * @type {boolean}
     * @memberof CartDiscountDraftDTO
     */
    isActive: boolean;
    /**
     * 
     * @type {number}
     * @memberof CartDiscountDraftDTO
     */
    validFrom?: number;
    /**
     * 
     * @type {number}
     * @memberof CartDiscountDraftDTO
     */
    validTo?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CartDiscountDraftDTO
     */
    requiresDiscountCode: boolean;
    /**
     * 
     * @type {string}
     * @memberof CartDiscountDraftDTO
     */
    stackingMode: string;
}

export function CartDiscountDraftDTOFromJSON(json: any): CartDiscountDraftDTO {
    return CartDiscountDraftDTOFromJSONTyped(json, false);
}

export function CartDiscountDraftDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartDiscountDraftDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authority': json['authority'],
        'merchantKey': !exists(json, 'merchantKey') ? undefined : json['merchantKey'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'value': CartDiscountValueDTOFromJSON(json['value']),
        'cartPredicate': json['cartPredicate'],
        'target': !exists(json, 'target') ? undefined : CartDiscountTargetDTOFromJSON(json['target']),
        'sortOrder': json['sortOrder'],
        'isActive': json['isActive'],
        'validFrom': !exists(json, 'validFrom') ? undefined : json['validFrom'],
        'validTo': !exists(json, 'validTo') ? undefined : json['validTo'],
        'requiresDiscountCode': json['requiresDiscountCode'],
        'stackingMode': json['stackingMode'],
    };
}

export function CartDiscountDraftDTOToJSON(value?: CartDiscountDraftDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authority': value.authority,
        'merchantKey': value.merchantKey,
        'name': value.name,
        'description': value.description,
        'value': CartDiscountValueDTOToJSON(value.value),
        'cartPredicate': value.cartPredicate,
        'target': CartDiscountTargetDTOToJSON(value.target),
        'sortOrder': value.sortOrder,
        'isActive': value.isActive,
        'validFrom': value.validFrom,
        'validTo': value.validTo,
        'requiresDiscountCode': value.requiresDiscountCode,
        'stackingMode': value.stackingMode,
    };
}

/**
* @export
* @enum {string}
*/
export enum CartDiscountDraftDTOAuthorityEnum {
    Platform = 'Platform',
    Merchant = 'Merchant'
}


