/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IdReferenceDTO,
    IdReferenceDTOFromJSON,
    IdReferenceDTOFromJSONTyped,
    IdReferenceDTOToJSON,
    MoneyDTO,
    MoneyDTOFromJSON,
    MoneyDTOFromJSONTyped,
    MoneyDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface CartDiscountValueDTO
 */
export interface CartDiscountValueDTO {
    /**
     * 
     * @type {string}
     * @memberof CartDiscountValueDTO
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof CartDiscountValueDTO
     */
    permyriad?: number;
    /**
     * 
     * @type {Array<MoneyDTO>}
     * @memberof CartDiscountValueDTO
     */
    money?: Array<MoneyDTO>;
    /**
     * 
     * @type {IdReferenceDTO}
     * @memberof CartDiscountValueDTO
     */
    product?: IdReferenceDTO;
    /**
     * 
     * @type {string}
     * @memberof CartDiscountValueDTO
     */
    variantId?: string;
    /**
     * 
     * @type {number}
     * @memberof CartDiscountValueDTO
     */
    quantity?: number;
}

export function CartDiscountValueDTOFromJSON(json: any): CartDiscountValueDTO {
    return CartDiscountValueDTOFromJSONTyped(json, false);
}

export function CartDiscountValueDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartDiscountValueDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'permyriad': !exists(json, 'permyriad') ? undefined : json['permyriad'],
        'money': !exists(json, 'money') ? undefined : ((json['money'] as Array<any>).map(MoneyDTOFromJSON)),
        'product': !exists(json, 'product') ? undefined : IdReferenceDTOFromJSON(json['product']),
        'variantId': !exists(json, 'variantId') ? undefined : json['variantId'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function CartDiscountValueDTOToJSON(value?: CartDiscountValueDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'permyriad': value.permyriad,
        'money': value.money === undefined ? undefined : ((value.money as Array<any>).map(MoneyDTOToJSON)),
        'product': IdReferenceDTOToJSON(value.product),
        'variantId': value.variantId,
        'quantity': value.quantity,
    };
}


