/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AssetDTO,
    AssetDTOFromJSON,
    AssetDTOFromJSONTyped,
    AssetDTOToJSON,
    IdLinkDTO,
    IdLinkDTOFromJSON,
    IdLinkDTOFromJSONTyped,
    IdLinkDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface CategoryDraftDTO
 */
export interface CategoryDraftDTO {
    /**
     * 
     * @type {number}
     * @memberof CategoryDraftDTO
     */
    version?: number;
    /**
     * 
     * @type {object}
     * @memberof CategoryDraftDTO
     */
    name: object;
    /**
     * 
     * @type {object}
     * @memberof CategoryDraftDTO
     */
    description?: object;
    /**
     * 
     * @type {number}
     * @memberof CategoryDraftDTO
     */
    weight: number;
    /**
     * 
     * @type {IdLinkDTO}
     * @memberof CategoryDraftDTO
     */
    parent?: IdLinkDTO;
    /**
     * 
     * @type {Array<IdLinkDTO>}
     * @memberof CategoryDraftDTO
     */
    ancestors?: Array<IdLinkDTO>;
    /**
     * 
     * @type {IdLinkDTO}
     * @memberof CategoryDraftDTO
     */
    alias?: IdLinkDTO;
    /**
     * 
     * @type {string}
     * @memberof CategoryDraftDTO
     */
    status: CategoryDraftDTOStatusEnum;
    /**
     * 
     * @type {Array<AssetDTO>}
     * @memberof CategoryDraftDTO
     */
    assets?: Array<AssetDTO>;
    /**
     * 
     * @type {object}
     * @memberof CategoryDraftDTO
     */
    slug: object;
    /**
     * 
     * @type {object}
     * @memberof CategoryDraftDTO
     */
    metaTitle?: object;
    /**
     * 
     * @type {object}
     * @memberof CategoryDraftDTO
     */
    metaDescription?: object;
    /**
     * 
     * @type {object}
     * @memberof CategoryDraftDTO
     */
    metaKeywords?: object;
    /**
     * 
     * @type {object}
     * @memberof CategoryDraftDTO
     */
    custom?: object;
    /**
     * 
     * @type {string}
     * @memberof CategoryDraftDTO
     */
    externalId?: string;
}

export function CategoryDraftDTOFromJSON(json: any): CategoryDraftDTO {
    return CategoryDraftDTOFromJSONTyped(json, false);
}

export function CategoryDraftDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryDraftDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'weight': json['weight'],
        'parent': !exists(json, 'parent') ? undefined : IdLinkDTOFromJSON(json['parent']),
        'ancestors': !exists(json, 'ancestors') ? undefined : ((json['ancestors'] as Array<any>).map(IdLinkDTOFromJSON)),
        'alias': !exists(json, 'alias') ? undefined : IdLinkDTOFromJSON(json['alias']),
        'status': json['status'],
        'assets': !exists(json, 'assets') ? undefined : ((json['assets'] as Array<any>).map(AssetDTOFromJSON)),
        'slug': json['slug'],
        'metaTitle': !exists(json, 'metaTitle') ? undefined : json['metaTitle'],
        'metaDescription': !exists(json, 'metaDescription') ? undefined : json['metaDescription'],
        'metaKeywords': !exists(json, 'metaKeywords') ? undefined : json['metaKeywords'],
        'custom': !exists(json, 'custom') ? undefined : json['custom'],
        'externalId': !exists(json, 'externalId') ? undefined : json['externalId'],
    };
}

export function CategoryDraftDTOToJSON(value?: CategoryDraftDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'name': value.name,
        'description': value.description,
        'weight': value.weight,
        'parent': IdLinkDTOToJSON(value.parent),
        'ancestors': value.ancestors === undefined ? undefined : ((value.ancestors as Array<any>).map(IdLinkDTOToJSON)),
        'alias': IdLinkDTOToJSON(value.alias),
        'status': value.status,
        'assets': value.assets === undefined ? undefined : ((value.assets as Array<any>).map(AssetDTOToJSON)),
        'slug': value.slug,
        'metaTitle': value.metaTitle,
        'metaDescription': value.metaDescription,
        'metaKeywords': value.metaKeywords,
        'custom': value.custom,
        'externalId': value.externalId,
    };
}

/**
* @export
* @enum {string}
*/
export enum CategoryDraftDTOStatusEnum {
    Published = 'published',
    Unpublished = 'unpublished',
    Delisted = 'delisted'
}


