/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerSubscriptionDTO
 */
export interface CustomerSubscriptionDTO {
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriptionDTO
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerSubscriptionDTO
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerSubscriptionDTO
     */
    updatedAt: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriptionDTO
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriptionDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerSubscriptionDTO
     */
    anonymousId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CustomerSubscriptionDTO
     */
    subscriptions: Array<string>;
}

export function CustomerSubscriptionDTOFromJSON(json: any): CustomerSubscriptionDTO {
    return CustomerSubscriptionDTOFromJSONTyped(json, false);
}

export function CustomerSubscriptionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerSubscriptionDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'customerId': !exists(json, 'customerId') ? undefined : json['customerId'],
        'email': json['email'],
        'anonymousId': !exists(json, 'anonymousId') ? undefined : json['anonymousId'],
        'subscriptions': json['subscriptions'],
    };
}

export function CustomerSubscriptionDTOToJSON(value?: CustomerSubscriptionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'customerId': value.customerId,
        'email': value.email,
        'anonymousId': value.anonymousId,
        'subscriptions': value.subscriptions,
    };
}


