/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerGroupDTO
 */
export interface CustomerGroupDTO {
    /**
     * 
     * @type {string}
     * @memberof CustomerGroupDTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerGroupDTO
     */
    label: string;
}

export function CustomerGroupDTOFromJSON(json: any): CustomerGroupDTO {
    return CustomerGroupDTOFromJSONTyped(json, false);
}

export function CustomerGroupDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerGroupDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'label': json['label'],
    };
}

export function CustomerGroupDTOToJSON(value?: CustomerGroupDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'label': value.label,
    };
}


