/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DiscountedLineItemPortionDTO,
    DiscountedLineItemPortionDTOFromJSON,
    DiscountedLineItemPortionDTOFromJSONTyped,
    DiscountedLineItemPortionDTOToJSON,
    MoneyDTO,
    MoneyDTOFromJSON,
    MoneyDTOFromJSONTyped,
    MoneyDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface DiscountedLineItemPriceDTO
 */
export interface DiscountedLineItemPriceDTO {
    /**
     * 
     * @type {MoneyDTO}
     * @memberof DiscountedLineItemPriceDTO
     */
    value: MoneyDTO;
    /**
     * 
     * @type {Array<DiscountedLineItemPortionDTO>}
     * @memberof DiscountedLineItemPriceDTO
     */
    includedDiscounts: Array<DiscountedLineItemPortionDTO>;
}

export function DiscountedLineItemPriceDTOFromJSON(json: any): DiscountedLineItemPriceDTO {
    return DiscountedLineItemPriceDTOFromJSONTyped(json, false);
}

export function DiscountedLineItemPriceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscountedLineItemPriceDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': MoneyDTOFromJSON(json['value']),
        'includedDiscounts': ((json['includedDiscounts'] as Array<any>).map(DiscountedLineItemPortionDTOFromJSON)),
    };
}

export function DiscountedLineItemPriceDTOToJSON(value?: DiscountedLineItemPriceDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': MoneyDTOToJSON(value.value),
        'includedDiscounts': ((value.includedDiscounts as Array<any>).map(DiscountedLineItemPortionDTOToJSON)),
    };
}


