/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdLinkDTO
 */
export interface IdLinkDTO {
    /**
     * 
     * @type {string}
     * @memberof IdLinkDTO
     */
    resourceId: string;
    /**
     * 
     * @type {string}
     * @memberof IdLinkDTO
     */
    resourceType: IdLinkDTOResourceTypeEnum;
}

export function IdLinkDTOFromJSON(json: any): IdLinkDTO {
    return IdLinkDTOFromJSONTyped(json, false);
}

export function IdLinkDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdLinkDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resourceId': json['resourceId'],
        'resourceType': json['resourceType'],
    };
}

export function IdLinkDTOToJSON(value?: IdLinkDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resourceId': value.resourceId,
        'resourceType': value.resourceType,
    };
}

/**
* @export
* @enum {string}
*/
export enum IdLinkDTOResourceTypeEnum {
    Store = 'store',
    Address = 'address',
    Brand = 'brand',
    Category = 'category',
    Collection = 'collection',
    View = 'view',
    Wallet = 'wallet',
    WalletType = 'wallet-type',
    Customer = 'customer',
    CustomerGroup = 'customer-group',
    ProductDiscount = 'product-discount',
    CartDiscount = 'cart-discount',
    DiscountCode = 'discount-code',
    Item = 'item',
    Order = 'order',
    Payment = 'payment',
    Merchant = 'merchant',
    Product = 'product',
    Shipping = 'shipping',
    TaxCategory = 'tax-category',
    PriceList = 'price-list',
    ShippingMethod = 'shipping-method',
    PaymentMethod = 'payment-method',
    State = 'state'
}


