/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdReferenceDTO
 */
export interface IdReferenceDTO {
    /**
     * 
     * @type {string}
     * @memberof IdReferenceDTO
     */
    resourceId: string;
    /**
     * 
     * @type {string}
     * @memberof IdReferenceDTO
     */
    resourceType: IdReferenceDTOResourceTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof IdReferenceDTO
     */
    resource?: object;
}

export function IdReferenceDTOFromJSON(json: any): IdReferenceDTO {
    return IdReferenceDTOFromJSONTyped(json, false);
}

export function IdReferenceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdReferenceDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resourceId': json['resourceId'],
        'resourceType': json['resourceType'],
        'resource': !exists(json, 'resource') ? undefined : json['resource'],
    };
}

export function IdReferenceDTOToJSON(value?: IdReferenceDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resourceId': value.resourceId,
        'resourceType': value.resourceType,
        'resource': value.resource,
    };
}

/**
* @export
* @enum {string}
*/
export enum IdReferenceDTOResourceTypeEnum {
    Store = 'store',
    Address = 'address',
    Brand = 'brand',
    Category = 'category',
    Collection = 'collection',
    View = 'view',
    Wallet = 'wallet',
    WalletType = 'wallet-type',
    Customer = 'customer',
    CustomerGroup = 'customer-group',
    ProductDiscount = 'product-discount',
    CartDiscount = 'cart-discount',
    DiscountCode = 'discount-code',
    Item = 'item',
    Order = 'order',
    Payment = 'payment',
    Merchant = 'merchant',
    Product = 'product',
    Shipping = 'shipping',
    TaxCategory = 'tax-category',
    PriceList = 'price-list',
    ShippingMethod = 'shipping-method',
    PaymentMethod = 'payment-method',
    State = 'state',
    CmsFolder = 'cms-folder',
    CmsType = 'cms-type'
}


