/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternationalsDTO
 */
export interface InternationalsDTO {
    /**
     * 
     * @type {Array<string>}
     * @memberof InternationalsDTO
     */
    currencies: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InternationalsDTO
     */
    languages: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InternationalsDTO
     */
    countries: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof InternationalsDTO
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof InternationalsDTO
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof InternationalsDTO
     */
    updatedAt: number;
}

export function InternationalsDTOFromJSON(json: any): InternationalsDTO {
    return InternationalsDTOFromJSONTyped(json, false);
}

export function InternationalsDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternationalsDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currencies': json['currencies'],
        'languages': json['languages'],
        'countries': json['countries'],
        'id': json['id'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function InternationalsDTOToJSON(value?: InternationalsDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currencies': value.currencies,
        'languages': value.languages,
        'countries': value.countries,
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
    };
}


