/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryUpdateDTO
 */
export interface InventoryUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof InventoryUpdateDTO
     */
    warehouseKey: string;
    /**
     * 
     * @type {string}
     * @memberof InventoryUpdateDTO
     */
    merchantKey: string;
    /**
     * 
     * @type {number}
     * @memberof InventoryUpdateDTO
     */
    quantity: number;
}

export function InventoryUpdateDTOFromJSON(json: any): InventoryUpdateDTO {
    return InventoryUpdateDTOFromJSONTyped(json, false);
}

export function InventoryUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'warehouseKey': json['warehouseKey'],
        'merchantKey': json['merchantKey'],
        'quantity': json['quantity'],
    };
}

export function InventoryUpdateDTOToJSON(value?: InventoryUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'warehouseKey': value.warehouseKey,
        'merchantKey': value.merchantKey,
        'quantity': value.quantity,
    };
}


