/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemShippingTargetDTO
 */
export interface ItemShippingTargetDTO {
    /**
     * 
     * @type {string}
     * @memberof ItemShippingTargetDTO
     */
    addressKey: string;
    /**
     * 
     * @type {number}
     * @memberof ItemShippingTargetDTO
     */
    quantity: number;
}

export function ItemShippingTargetDTOFromJSON(json: any): ItemShippingTargetDTO {
    return ItemShippingTargetDTOFromJSONTyped(json, false);
}

export function ItemShippingTargetDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemShippingTargetDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addressKey': json['addressKey'],
        'quantity': json['quantity'],
    };
}

export function ItemShippingTargetDTOToJSON(value?: ItemShippingTargetDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addressKey': value.addressKey,
        'quantity': value.quantity,
    };
}


