/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DiscountedLineItemPriceForQuantity,
    DiscountedLineItemPriceForQuantityFromJSON,
    DiscountedLineItemPriceForQuantityFromJSONTyped,
    DiscountedLineItemPriceForQuantityToJSON,
    IdReferenceDTO,
    IdReferenceDTOFromJSON,
    IdReferenceDTOFromJSONTyped,
    IdReferenceDTOToJSON,
    ItemShippingDetailsDTO,
    ItemShippingDetailsDTOFromJSON,
    ItemShippingDetailsDTOFromJSONTyped,
    ItemShippingDetailsDTOToJSON,
    LineItemStateForQuantityDTO,
    LineItemStateForQuantityDTOFromJSON,
    LineItemStateForQuantityDTOFromJSONTyped,
    LineItemStateForQuantityDTOToJSON,
    MoneyDTO,
    MoneyDTOFromJSON,
    MoneyDTOFromJSONTyped,
    MoneyDTOToJSON,
    OfferDTO,
    OfferDTOFromJSON,
    OfferDTOFromJSONTyped,
    OfferDTOToJSON,
    ProductVariantDTO,
    ProductVariantDTOFromJSON,
    ProductVariantDTOFromJSONTyped,
    ProductVariantDTOToJSON,
    TaxRateDTO,
    TaxRateDTOFromJSON,
    TaxRateDTOFromJSONTyped,
    TaxRateDTOToJSON,
    TaxedItemPriceDTO,
    TaxedItemPriceDTOFromJSON,
    TaxedItemPriceDTOFromJSONTyped,
    TaxedItemPriceDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface LineItemDTO
 */
export interface LineItemDTO {
    /**
     * 
     * @type {number}
     * @memberof LineItemDTO
     */
    updatedAt: number;
    /**
     * 
     * @type {string}
     * @memberof LineItemDTO
     */
    id: string;
    /**
     * 
     * @type {Array<LineItemStateForQuantityDTO>}
     * @memberof LineItemDTO
     */
    states: Array<LineItemStateForQuantityDTO>;
    /**
     * 
     * @type {string}
     * @memberof LineItemDTO
     */
    productId: string;
    /**
     * 
     * @type {object}
     * @memberof LineItemDTO
     */
    productName: object;
    /**
     * 
     * @type {object}
     * @memberof LineItemDTO
     */
    productSlug: object;
    /**
     * 
     * @type {string}
     * @memberof LineItemDTO
     */
    productThumbnailUrl: string;
    /**
     * 
     * @type {Array<IdReferenceDTO>}
     * @memberof LineItemDTO
     */
    productCategories?: Array<IdReferenceDTO>;
    /**
     * 
     * @type {Array<IdReferenceDTO>}
     * @memberof LineItemDTO
     */
    productBrands?: Array<IdReferenceDTO>;
    /**
     * 
     * @type {Array<IdReferenceDTO>}
     * @memberof LineItemDTO
     */
    productCollections?: Array<IdReferenceDTO>;
    /**
     * 
     * @type {IdReferenceDTO}
     * @memberof LineItemDTO
     */
    productTaxCategory: IdReferenceDTO;
    /**
     * 
     * @type {ProductVariantDTO}
     * @memberof LineItemDTO
     */
    variant: ProductVariantDTO;
    /**
     * 
     * @type {OfferDTO}
     * @memberof LineItemDTO
     */
    offer: OfferDTO;
    /**
     * 
     * @type {number}
     * @memberof LineItemDTO
     */
    quantity: number;
    /**
     * 
     * @type {TaxedItemPriceDTO}
     * @memberof LineItemDTO
     */
    taxedPrice?: TaxedItemPriceDTO;
    /**
     * 
     * @type {TaxRateDTO}
     * @memberof LineItemDTO
     */
    taxRate?: TaxRateDTO;
    /**
     * 
     * @type {MoneyDTO}
     * @memberof LineItemDTO
     */
    totalPrice?: MoneyDTO;
    /**
     * 
     * @type {Array<DiscountedLineItemPriceForQuantity>}
     * @memberof LineItemDTO
     */
    discountedPricePerQuantity?: Array<DiscountedLineItemPriceForQuantity>;
    /**
     * 
     * @type {string}
     * @memberof LineItemDTO
     */
    lineItemMode: LineItemDTOLineItemModeEnum;
    /**
     * 
     * @type {ItemShippingDetailsDTO}
     * @memberof LineItemDTO
     */
    shippingDetails?: ItemShippingDetailsDTO;
}

export function LineItemDTOFromJSON(json: any): LineItemDTO {
    return LineItemDTOFromJSONTyped(json, false);
}

export function LineItemDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineItemDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'updatedAt': json['updatedAt'],
        'id': json['id'],
        'states': ((json['states'] as Array<any>).map(LineItemStateForQuantityDTOFromJSON)),
        'productId': json['productId'],
        'productName': json['productName'],
        'productSlug': json['productSlug'],
        'productThumbnailUrl': json['productThumbnailUrl'],
        'productCategories': !exists(json, 'productCategories') ? undefined : ((json['productCategories'] as Array<any>).map(IdReferenceDTOFromJSON)),
        'productBrands': !exists(json, 'productBrands') ? undefined : ((json['productBrands'] as Array<any>).map(IdReferenceDTOFromJSON)),
        'productCollections': !exists(json, 'productCollections') ? undefined : ((json['productCollections'] as Array<any>).map(IdReferenceDTOFromJSON)),
        'productTaxCategory': IdReferenceDTOFromJSON(json['productTaxCategory']),
        'variant': ProductVariantDTOFromJSON(json['variant']),
        'offer': OfferDTOFromJSON(json['offer']),
        'quantity': json['quantity'],
        'taxedPrice': !exists(json, 'taxedPrice') ? undefined : TaxedItemPriceDTOFromJSON(json['taxedPrice']),
        'taxRate': !exists(json, 'taxRate') ? undefined : TaxRateDTOFromJSON(json['taxRate']),
        'totalPrice': !exists(json, 'totalPrice') ? undefined : MoneyDTOFromJSON(json['totalPrice']),
        'discountedPricePerQuantity': !exists(json, 'discountedPricePerQuantity') ? undefined : ((json['discountedPricePerQuantity'] as Array<any>).map(DiscountedLineItemPriceForQuantityFromJSON)),
        'lineItemMode': json['lineItemMode'],
        'shippingDetails': !exists(json, 'shippingDetails') ? undefined : ItemShippingDetailsDTOFromJSON(json['shippingDetails']),
    };
}

export function LineItemDTOToJSON(value?: LineItemDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'updatedAt': value.updatedAt,
        'id': value.id,
        'states': ((value.states as Array<any>).map(LineItemStateForQuantityDTOToJSON)),
        'productId': value.productId,
        'productName': value.productName,
        'productSlug': value.productSlug,
        'productThumbnailUrl': value.productThumbnailUrl,
        'productCategories': value.productCategories === undefined ? undefined : ((value.productCategories as Array<any>).map(IdReferenceDTOToJSON)),
        'productBrands': value.productBrands === undefined ? undefined : ((value.productBrands as Array<any>).map(IdReferenceDTOToJSON)),
        'productCollections': value.productCollections === undefined ? undefined : ((value.productCollections as Array<any>).map(IdReferenceDTOToJSON)),
        'productTaxCategory': IdReferenceDTOToJSON(value.productTaxCategory),
        'variant': ProductVariantDTOToJSON(value.variant),
        'offer': OfferDTOToJSON(value.offer),
        'quantity': value.quantity,
        'taxedPrice': TaxedItemPriceDTOToJSON(value.taxedPrice),
        'taxRate': TaxRateDTOToJSON(value.taxRate),
        'totalPrice': MoneyDTOToJSON(value.totalPrice),
        'discountedPricePerQuantity': value.discountedPricePerQuantity === undefined ? undefined : ((value.discountedPricePerQuantity as Array<any>).map(DiscountedLineItemPriceForQuantityToJSON)),
        'lineItemMode': value.lineItemMode,
        'shippingDetails': ItemShippingDetailsDTOToJSON(value.shippingDetails),
    };
}

/**
* @export
* @enum {string}
*/
export enum LineItemDTOLineItemModeEnum {
    Standard = 'Standard',
    Gift = 'Gift'
}


