/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MerchantDraftDTO
 */
export interface MerchantDraftDTO {
    /**
     * 
     * @type {number}
     * @memberof MerchantDraftDTO
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof MerchantDraftDTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantDraftDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantDraftDTO
     */
    description?: string;
}

export function MerchantDraftDTOFromJSON(json: any): MerchantDraftDTO {
    return MerchantDraftDTOFromJSONTyped(json, false);
}

export function MerchantDraftDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantDraftDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'key': json['key'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function MerchantDraftDTOToJSON(value?: MerchantDraftDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'key': value.key,
        'name': value.name,
        'description': value.description,
    };
}


