/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IdReferenceDTO,
    IdReferenceDTOFromJSON,
    IdReferenceDTOFromJSONTyped,
    IdReferenceDTOToJSON,
    KeyReferenceDTO,
    KeyReferenceDTOFromJSON,
    KeyReferenceDTOFromJSONTyped,
    KeyReferenceDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface MerchantMethodDTO
 */
export interface MerchantMethodDTO {
    /**
     * 
     * @type {KeyReferenceDTO}
     * @memberof MerchantMethodDTO
     */
    merchant: KeyReferenceDTO;
    /**
     * 
     * @type {IdReferenceDTO}
     * @memberof MerchantMethodDTO
     */
    method: IdReferenceDTO;
}

export function MerchantMethodDTOFromJSON(json: any): MerchantMethodDTO {
    return MerchantMethodDTOFromJSONTyped(json, false);
}

export function MerchantMethodDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantMethodDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'merchant': KeyReferenceDTOFromJSON(json['merchant']),
        'method': IdReferenceDTOFromJSON(json['method']),
    };
}

export function MerchantMethodDTOToJSON(value?: MerchantMethodDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'merchant': KeyReferenceDTOToJSON(value.merchant),
        'method': IdReferenceDTOToJSON(value.method),
    };
}


