/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MoneyDTO,
    MoneyDTOFromJSON,
    MoneyDTOFromJSONTyped,
    MoneyDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface MerchantPriceDTO
 */
export interface MerchantPriceDTO {
    /**
     * 
     * @type {string}
     * @memberof MerchantPriceDTO
     */
    merchantKey: string;
    /**
     * 
     * @type {MoneyDTO}
     * @memberof MerchantPriceDTO
     */
    price: MoneyDTO;
}

export function MerchantPriceDTOFromJSON(json: any): MerchantPriceDTO {
    return MerchantPriceDTOFromJSONTyped(json, false);
}

export function MerchantPriceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantPriceDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'merchantKey': json['merchantKey'],
        'price': MoneyDTOFromJSON(json['price']),
    };
}

export function MerchantPriceDTOToJSON(value?: MerchantPriceDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'merchantKey': value.merchantKey,
        'price': MoneyDTOToJSON(value.price),
    };
}


