/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MerchantMethodDTO,
    MerchantMethodDTOFromJSON,
    MerchantMethodDTOFromJSONTyped,
    MerchantMethodDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface MerchantsMethodsUpdateDTO
 */
export interface MerchantsMethodsUpdateDTO {
    /**
     * 
     * @type {Array<MerchantMethodDTO>}
     * @memberof MerchantsMethodsUpdateDTO
     */
    methods: Array<MerchantMethodDTO>;
}

export function MerchantsMethodsUpdateDTOFromJSON(json: any): MerchantsMethodsUpdateDTO {
    return MerchantsMethodsUpdateDTOFromJSONTyped(json, false);
}

export function MerchantsMethodsUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantsMethodsUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'methods': ((json['methods'] as Array<any>).map(MerchantMethodDTOFromJSON)),
    };
}

export function MerchantsMethodsUpdateDTOToJSON(value?: MerchantsMethodsUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'methods': ((value.methods as Array<any>).map(MerchantMethodDTOToJSON)),
    };
}


