/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageDTO
 */
export interface MessageDTO {
    /**
     * 
     * @type {string}
     * @memberof MessageDTO
     */
    resourceTypeId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MessageDTO
     */
    types: Array<string>;
}

export function MessageDTOFromJSON(json: any): MessageDTO {
    return MessageDTOFromJSONTyped(json, false);
}

export function MessageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resourceTypeId': json['resourceTypeId'],
        'types': json['types'],
    };
}

export function MessageDTOToJSON(value?: MessageDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resourceTypeId': value.resourceTypeId,
        'types': value.types,
    };
}


