/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OfferUpdateDTO
 */
export interface OfferUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof OfferUpdateDTO
     */
    priceListKey: string;
    /**
     * 
     * @type {string}
     * @memberof OfferUpdateDTO
     */
    merchantKey: string;
    /**
     * 
     * @type {number}
     * @memberof OfferUpdateDTO
     */
    priceCentAmount: number;
    /**
     * 
     * @type {number}
     * @memberof OfferUpdateDTO
     */
    discountedPriceCentAmount: number;
}

export function OfferUpdateDTOFromJSON(json: any): OfferUpdateDTO {
    return OfferUpdateDTOFromJSONTyped(json, false);
}

export function OfferUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfferUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'priceListKey': json['priceListKey'],
        'merchantKey': json['merchantKey'],
        'priceCentAmount': json['priceCentAmount'],
        'discountedPriceCentAmount': json['discountedPriceCentAmount'],
    };
}

export function OfferUpdateDTOToJSON(value?: OfferUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'priceListKey': value.priceListKey,
        'merchantKey': value.merchantKey,
        'priceCentAmount': value.priceCentAmount,
        'discountedPriceCentAmount': value.discountedPriceCentAmount,
    };
}


