/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IdReferenceDTO,
    IdReferenceDTOFromJSON,
    IdReferenceDTOFromJSONTyped,
    IdReferenceDTOToJSON,
    MoneyDTO,
    MoneyDTOFromJSON,
    MoneyDTOFromJSONTyped,
    MoneyDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface OrderWalletDTO
 */
export interface OrderWalletDTO {
    /**
     * 
     * @type {IdReferenceDTO}
     * @memberof OrderWalletDTO
     */
    wallet: IdReferenceDTO;
    /**
     * 
     * @type {MoneyDTO}
     * @memberof OrderWalletDTO
     */
    discount?: MoneyDTO;
}

export function OrderWalletDTOFromJSON(json: any): OrderWalletDTO {
    return OrderWalletDTOFromJSONTyped(json, false);
}

export function OrderWalletDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderWalletDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'wallet': IdReferenceDTOFromJSON(json['wallet']),
        'discount': !exists(json, 'discount') ? undefined : MoneyDTOFromJSON(json['discount']),
    };
}

export function OrderWalletDTOToJSON(value?: OrderWalletDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'wallet': IdReferenceDTOToJSON(value.wallet),
        'discount': MoneyDTOToJSON(value.discount),
    };
}


