/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentInterfaceInteractionDraftDTO
 */
export interface PaymentInterfaceInteractionDraftDTO {
    /**
     * 
     * @type {object}
     * @memberof PaymentInterfaceInteractionDraftDTO
     */
    interactionPayload: object;
}

export function PaymentInterfaceInteractionDraftDTOFromJSON(json: any): PaymentInterfaceInteractionDraftDTO {
    return PaymentInterfaceInteractionDraftDTOFromJSONTyped(json, false);
}

export function PaymentInterfaceInteractionDraftDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentInterfaceInteractionDraftDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'interactionPayload': json['interactionPayload'],
    };
}

export function PaymentInterfaceInteractionDraftDTOToJSON(value?: PaymentInterfaceInteractionDraftDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'interactionPayload': value.interactionPayload,
    };
}


