/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MoneyDTO,
    MoneyDTOFromJSON,
    MoneyDTOFromJSONTyped,
    MoneyDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface PaymentTransactionDraftDTO
 */
export interface PaymentTransactionDraftDTO {
    /**
     * 
     * @type {object}
     * @memberof PaymentTransactionDraftDTO
     */
    id?: object;
    /**
     * 
     * @type {string}
     * @memberof PaymentTransactionDraftDTO
     */
    status?: PaymentTransactionDraftDTOStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentTransactionDraftDTO
     */
    type: PaymentTransactionDraftDTOTypeEnum;
    /**
     * 
     * @type {MoneyDTO}
     * @memberof PaymentTransactionDraftDTO
     */
    amount: MoneyDTO;
    /**
     * 
     * @type {string}
     * @memberof PaymentTransactionDraftDTO
     */
    transactionNumber: string;
    /**
     * 
     * @type {object}
     * @memberof PaymentTransactionDraftDTO
     */
    providerPayload?: object;
}

export function PaymentTransactionDraftDTOFromJSON(json: any): PaymentTransactionDraftDTO {
    return PaymentTransactionDraftDTOFromJSONTyped(json, false);
}

export function PaymentTransactionDraftDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentTransactionDraftDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, '_id') ? undefined : json['_id'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'type': json['type'],
        'amount': MoneyDTOFromJSON(json['amount']),
        'transactionNumber': json['transactionNumber'],
        'providerPayload': !exists(json, 'providerPayload') ? undefined : json['providerPayload'],
    };
}

export function PaymentTransactionDraftDTOToJSON(value?: PaymentTransactionDraftDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_id': value.id,
        'status': value.status,
        'type': value.type,
        'amount': MoneyDTOToJSON(value.amount),
        'transactionNumber': value.transactionNumber,
        'providerPayload': value.providerPayload,
    };
}

/**
* @export
* @enum {string}
*/
export enum PaymentTransactionDraftDTOStatusEnum {
    Initial = 'Initial',
    Pending = 'Pending',
    Success = 'Success',
    Failure = 'Failure'
}
/**
* @export
* @enum {string}
*/
export enum PaymentTransactionDraftDTOTypeEnum {
    Authorization = 'Authorization',
    CancelAuthorization = 'CancelAuthorization',
    Charge = 'Charge',
    Refund = 'Refund',
    ChargeBack = 'ChargeBack'
}


