/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentMethodDraftDTO
 */
export interface PaymentMethodDraftDTO {
    /**
     * 
     * @type {number}
     * @memberof PaymentMethodDraftDTO
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodDraftDTO
     */
    authority: PaymentMethodDraftDTOAuthorityEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodDraftDTO
     */
    type: PaymentMethodDraftDTOTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodDraftDTO
     */
    providerType: PaymentMethodDraftDTOProviderTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodDraftDTO
     */
    merchantKey?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodDraftDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodDraftDTO
     */
    countryCode: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodDraftDTO
     */
    currencyCode: string;
    /**
     * 
     * @type {object}
     * @memberof PaymentMethodDraftDTO
     */
    providerConfig: object;
}

export function PaymentMethodDraftDTOFromJSON(json: any): PaymentMethodDraftDTO {
    return PaymentMethodDraftDTOFromJSONTyped(json, false);
}

export function PaymentMethodDraftDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodDraftDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'authority': json['authority'],
        'type': json['type'],
        'providerType': json['providerType'],
        'merchantKey': !exists(json, 'merchantKey') ? undefined : json['merchantKey'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'countryCode': json['countryCode'],
        'currencyCode': json['currencyCode'],
        'providerConfig': json['providerConfig'],
    };
}

export function PaymentMethodDraftDTOToJSON(value?: PaymentMethodDraftDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'authority': value.authority,
        'type': value.type,
        'providerType': value.providerType,
        'merchantKey': value.merchantKey,
        'description': value.description,
        'countryCode': value.countryCode,
        'currencyCode': value.currencyCode,
        'providerConfig': value.providerConfig,
    };
}

/**
* @export
* @enum {string}
*/
export enum PaymentMethodDraftDTOAuthorityEnum {
    Platform = 'Platform',
    Merchant = 'Merchant'
}
/**
* @export
* @enum {string}
*/
export enum PaymentMethodDraftDTOTypeEnum {
    PaymentServiceProvider = 'PaymentServiceProvider',
    CashOnDelivery = 'CashOnDelivery'
}
/**
* @export
* @enum {string}
*/
export enum PaymentMethodDraftDTOProviderTypeEnum {
    Borica = 'Borica'
}


