/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ImageSetDTO,
    ImageSetDTOFromJSON,
    ImageSetDTOFromJSONTyped,
    ImageSetDTOToJSON,
    InventoryDTO,
    InventoryDTOFromJSON,
    InventoryDTOFromJSONTyped,
    InventoryDTOToJSON,
    OfferDraftDTO,
    OfferDraftDTOFromJSON,
    OfferDraftDTOFromJSONTyped,
    OfferDraftDTOToJSON,
    ProductAttributeDTO,
    ProductAttributeDTOFromJSON,
    ProductAttributeDTOFromJSONTyped,
    ProductAttributeDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductVariantDraftDTO
 */
export interface ProductVariantDraftDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductVariantDraftDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantDraftDTO
     */
    sku: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantDraftDTO
     */
    masterBarcode?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductVariantDraftDTO
     */
    barcodes: Array<string>;
    /**
     * 
     * @type {Array<OfferDraftDTO>}
     * @memberof ProductVariantDraftDTO
     */
    offers: Array<OfferDraftDTO>;
    /**
     * 
     * @type {Array<InventoryDTO>}
     * @memberof ProductVariantDraftDTO
     */
    inventories: Array<InventoryDTO>;
    /**
     * 
     * @type {Array<ProductAttributeDTO>}
     * @memberof ProductVariantDraftDTO
     */
    attributes: Array<ProductAttributeDTO>;
    /**
     * 
     * @type {Array<ImageSetDTO>}
     * @memberof ProductVariantDraftDTO
     */
    imageSets: Array<ImageSetDTO>;
    /**
     * 
     * @type {number}
     * @memberof ProductVariantDraftDTO
     */
    weight?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantDraftDTO
     */
    unitOfWeight?: ProductVariantDraftDTOUnitOfWeightEnum;
    /**
     * 
     * @type {number}
     * @memberof ProductVariantDraftDTO
     */
    length?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductVariantDraftDTO
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductVariantDraftDTO
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantDraftDTO
     */
    unitOfMetric?: ProductVariantDraftDTOUnitOfMetricEnum;
}

export function ProductVariantDraftDTOFromJSON(json: any): ProductVariantDraftDTO {
    return ProductVariantDraftDTOFromJSONTyped(json, false);
}

export function ProductVariantDraftDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductVariantDraftDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sku': json['sku'],
        'masterBarcode': !exists(json, 'masterBarcode') ? undefined : json['masterBarcode'],
        'barcodes': json['barcodes'],
        'offers': ((json['offers'] as Array<any>).map(OfferDraftDTOFromJSON)),
        'inventories': ((json['inventories'] as Array<any>).map(InventoryDTOFromJSON)),
        'attributes': ((json['attributes'] as Array<any>).map(ProductAttributeDTOFromJSON)),
        'imageSets': ((json['imageSets'] as Array<any>).map(ImageSetDTOFromJSON)),
        'weight': !exists(json, 'weight') ? undefined : json['weight'],
        'unitOfWeight': !exists(json, 'unitOfWeight') ? undefined : json['unitOfWeight'],
        'length': !exists(json, 'length') ? undefined : json['length'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'unitOfMetric': !exists(json, 'unitOfMetric') ? undefined : json['unitOfMetric'],
    };
}

export function ProductVariantDraftDTOToJSON(value?: ProductVariantDraftDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'sku': value.sku,
        'masterBarcode': value.masterBarcode,
        'barcodes': value.barcodes,
        'offers': ((value.offers as Array<any>).map(OfferDraftDTOToJSON)),
        'inventories': ((value.inventories as Array<any>).map(InventoryDTOToJSON)),
        'attributes': ((value.attributes as Array<any>).map(ProductAttributeDTOToJSON)),
        'imageSets': ((value.imageSets as Array<any>).map(ImageSetDTOToJSON)),
        'weight': value.weight,
        'unitOfWeight': value.unitOfWeight,
        'length': value.length,
        'width': value.width,
        'height': value.height,
        'unitOfMetric': value.unitOfMetric,
    };
}

/**
* @export
* @enum {string}
*/
export enum ProductVariantDraftDTOUnitOfWeightEnum {
    Gr = 'gr',
    Oz = 'oz'
}
/**
* @export
* @enum {string}
*/
export enum ProductVariantDraftDTOUnitOfMetricEnum {
    Cm = 'cm',
    Inch = 'inch'
}


