/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductAttributeDTO
 */
export interface ProductAttributeDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductAttributeDTO
     */
    attributeName: string;
    /**
     * 
     * @type {object}
     * @memberof ProductAttributeDTO
     */
    value: object;
}

export function ProductAttributeDTOFromJSON(json: any): ProductAttributeDTO {
    return ProductAttributeDTOFromJSONTyped(json, false);
}

export function ProductAttributeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductAttributeDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributeName': json['attributeName'],
        'value': json['value'],
    };
}

export function ProductAttributeDTOToJSON(value?: ProductAttributeDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributeName': value.attributeName,
        'value': value.value,
    };
}


