/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MoneyDTO,
    MoneyDTOFromJSON,
    MoneyDTOFromJSONTyped,
    MoneyDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductDiscountValueDTO
 */
export interface ProductDiscountValueDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductDiscountValueDTO
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof ProductDiscountValueDTO
     */
    permyriad: number;
    /**
     * 
     * @type {Array<MoneyDTO>}
     * @memberof ProductDiscountValueDTO
     */
    money: Array<MoneyDTO>;
}

export function ProductDiscountValueDTOFromJSON(json: any): ProductDiscountValueDTO {
    return ProductDiscountValueDTOFromJSONTyped(json, false);
}

export function ProductDiscountValueDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDiscountValueDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'permyriad': json['permyriad'],
        'money': ((json['money'] as Array<any>).map(MoneyDTOFromJSON)),
    };
}

export function ProductDiscountValueDTOToJSON(value?: ProductDiscountValueDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'permyriad': value.permyriad,
        'money': ((value.money as Array<any>).map(MoneyDTOToJSON)),
    };
}


