/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProductDiscountValueDTO,
    ProductDiscountValueDTOFromJSON,
    ProductDiscountValueDTOFromJSONTyped,
    ProductDiscountValueDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductDiscountDTO
 */
export interface ProductDiscountDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductDiscountDTO
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof ProductDiscountDTO
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDiscountDTO
     */
    updatedAt: number;
    /**
     * 
     * @type {string}
     * @memberof ProductDiscountDTO
     */
    authority: ProductDiscountDTOAuthorityEnum;
    /**
     * 
     * @type {string}
     * @memberof ProductDiscountDTO
     */
    merchantKey?: string;
    /**
     * 
     * @type {object}
     * @memberof ProductDiscountDTO
     */
    name: object;
    /**
     * 
     * @type {object}
     * @memberof ProductDiscountDTO
     */
    description?: object;
    /**
     * 
     * @type {ProductDiscountValueDTO}
     * @memberof ProductDiscountDTO
     */
    value: ProductDiscountValueDTO;
    /**
     * 
     * @type {string}
     * @memberof ProductDiscountDTO
     */
    predicate: string;
    /**
     * 
     * @type {number}
     * @memberof ProductDiscountDTO
     */
    sortOrder: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductDiscountDTO
     */
    isActive: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProductDiscountDTO
     */
    validFrom?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDiscountDTO
     */
    validTo?: number;
}

export function ProductDiscountDTOFromJSON(json: any): ProductDiscountDTO {
    return ProductDiscountDTOFromJSONTyped(json, false);
}

export function ProductDiscountDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDiscountDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'authority': json['authority'],
        'merchantKey': !exists(json, 'merchantKey') ? undefined : json['merchantKey'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'value': ProductDiscountValueDTOFromJSON(json['value']),
        'predicate': json['predicate'],
        'sortOrder': json['sortOrder'],
        'isActive': json['isActive'],
        'validFrom': !exists(json, 'validFrom') ? undefined : json['validFrom'],
        'validTo': !exists(json, 'validTo') ? undefined : json['validTo'],
    };
}

export function ProductDiscountDTOToJSON(value?: ProductDiscountDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'authority': value.authority,
        'merchantKey': value.merchantKey,
        'name': value.name,
        'description': value.description,
        'value': ProductDiscountValueDTOToJSON(value.value),
        'predicate': value.predicate,
        'sortOrder': value.sortOrder,
        'isActive': value.isActive,
        'validFrom': value.validFrom,
        'validTo': value.validTo,
    };
}

/**
* @export
* @enum {string}
*/
export enum ProductDiscountDTOAuthorityEnum {
    Platform = 'Platform',
    Merchant = 'Merchant'
}


