/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MerchantShippingMethodsInfoDTO,
    MerchantShippingMethodsInfoDTOFromJSON,
    MerchantShippingMethodsInfoDTOFromJSONTyped,
    MerchantShippingMethodsInfoDTOToJSON,
    ShippingMethodDTO,
    ShippingMethodDTOFromJSON,
    ShippingMethodDTOFromJSONTyped,
    ShippingMethodDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface ShippingMethodsInfo
 */
export interface ShippingMethodsInfo {
    /**
     * 
     * @type {Array<ShippingMethodDTO>}
     * @memberof ShippingMethodsInfo
     */
    platformShippingMethods: Array<ShippingMethodDTO>;
    /**
     * 
     * @type {Array<MerchantShippingMethodsInfoDTO>}
     * @memberof ShippingMethodsInfo
     */
    merchantsShippingMethods: Array<MerchantShippingMethodsInfoDTO>;
}

export function ShippingMethodsInfoFromJSON(json: any): ShippingMethodsInfo {
    return ShippingMethodsInfoFromJSONTyped(json, false);
}

export function ShippingMethodsInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingMethodsInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'platformShippingMethods': ((json['platformShippingMethods'] as Array<any>).map(ShippingMethodDTOFromJSON)),
        'merchantsShippingMethods': ((json['merchantsShippingMethods'] as Array<any>).map(MerchantShippingMethodsInfoDTOFromJSON)),
    };
}

export function ShippingMethodsInfoToJSON(value?: ShippingMethodsInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'platformShippingMethods': ((value.platformShippingMethods as Array<any>).map(ShippingMethodDTOToJSON)),
        'merchantsShippingMethods': ((value.merchantsShippingMethods as Array<any>).map(MerchantShippingMethodsInfoDTOToJSON)),
    };
}


