/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CodFeeTableOrderTotalAmountDTO,
    CodFeeTableOrderTotalAmountDTOFromJSON,
    CodFeeTableOrderTotalAmountDTOFromJSONTyped,
    CodFeeTableOrderTotalAmountDTOToJSON,
    IdReferenceDTO,
    IdReferenceDTOFromJSON,
    IdReferenceDTOFromJSONTyped,
    IdReferenceDTOToJSON,
    ShippingFeeTableOrderTotalWeightInGramsDTO,
    ShippingFeeTableOrderTotalWeightInGramsDTOFromJSON,
    ShippingFeeTableOrderTotalWeightInGramsDTOFromJSONTyped,
    ShippingFeeTableOrderTotalWeightInGramsDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface ShippingMethodDraftDTO
 */
export interface ShippingMethodDraftDTO {
    /**
     * 
     * @type {number}
     * @memberof ShippingMethodDraftDTO
     */
    version?: number;
    /**
     * 
     * @type {object}
     * @memberof ShippingMethodDraftDTO
     */
    name: object;
    /**
     * 
     * @type {object}
     * @memberof ShippingMethodDraftDTO
     */
    description?: object;
    /**
     * 
     * @type {string}
     * @memberof ShippingMethodDraftDTO
     */
    authority: ShippingMethodDraftDTOAuthorityEnum;
    /**
     * 
     * @type {string}
     * @memberof ShippingMethodDraftDTO
     */
    type: ShippingMethodDraftDTOTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ShippingMethodDraftDTO
     */
    providerType: ShippingMethodDraftDTOProviderTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof ShippingMethodDraftDTO
     */
    option?: object;
    /**
     * 
     * @type {string}
     * @memberof ShippingMethodDraftDTO
     */
    merchantKey?: string;
    /**
     * 
     * @type {IdReferenceDTO}
     * @memberof ShippingMethodDraftDTO
     */
    taxCategory: IdReferenceDTO;
    /**
     * 
     * @type {string}
     * @memberof ShippingMethodDraftDTO
     */
    countryCode: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingMethodDraftDTO
     */
    currencyCode: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingMethodDraftDTO
     */
    shippingFeeRateCalculationType: ShippingMethodDraftDTOShippingFeeRateCalculationTypeEnum;
    /**
     * 
     * @type {Array<ShippingFeeTableOrderTotalWeightInGramsDTO>}
     * @memberof ShippingMethodDraftDTO
     */
    shippingFeeTableOrderTotalWeightInGrams: Array<ShippingFeeTableOrderTotalWeightInGramsDTO>;
    /**
     * 
     * @type {boolean}
     * @memberof ShippingMethodDraftDTO
     */
    isCOD: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShippingMethodDraftDTO
     */
    codFeeRateCalculationType: ShippingMethodDraftDTOCodFeeRateCalculationTypeEnum;
    /**
     * 
     * @type {Array<CodFeeTableOrderTotalAmountDTO>}
     * @memberof ShippingMethodDraftDTO
     */
    codFeeTableOrderTotalAmount: Array<CodFeeTableOrderTotalAmountDTO>;
    /**
     * 
     * @type {object}
     * @memberof ShippingMethodDraftDTO
     */
    providerConfig: object;
}

export function ShippingMethodDraftDTOFromJSON(json: any): ShippingMethodDraftDTO {
    return ShippingMethodDraftDTOFromJSONTyped(json, false);
}

export function ShippingMethodDraftDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingMethodDraftDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'authority': json['authority'],
        'type': json['type'],
        'providerType': json['providerType'],
        'option': !exists(json, 'option') ? undefined : json['option'],
        'merchantKey': !exists(json, 'merchantKey') ? undefined : json['merchantKey'],
        'taxCategory': IdReferenceDTOFromJSON(json['taxCategory']),
        'countryCode': json['countryCode'],
        'currencyCode': json['currencyCode'],
        'shippingFeeRateCalculationType': json['shippingFeeRateCalculationType'],
        'shippingFeeTableOrderTotalWeightInGrams': ((json['shippingFeeTableOrderTotalWeightInGrams'] as Array<any>).map(ShippingFeeTableOrderTotalWeightInGramsDTOFromJSON)),
        'isCOD': json['isCOD'],
        'codFeeRateCalculationType': json['codFeeRateCalculationType'],
        'codFeeTableOrderTotalAmount': ((json['codFeeTableOrderTotalAmount'] as Array<any>).map(CodFeeTableOrderTotalAmountDTOFromJSON)),
        'providerConfig': json['providerConfig'],
    };
}

export function ShippingMethodDraftDTOToJSON(value?: ShippingMethodDraftDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'name': value.name,
        'description': value.description,
        'authority': value.authority,
        'type': value.type,
        'providerType': value.providerType,
        'option': value.option,
        'merchantKey': value.merchantKey,
        'taxCategory': IdReferenceDTOToJSON(value.taxCategory),
        'countryCode': value.countryCode,
        'currencyCode': value.currencyCode,
        'shippingFeeRateCalculationType': value.shippingFeeRateCalculationType,
        'shippingFeeTableOrderTotalWeightInGrams': ((value.shippingFeeTableOrderTotalWeightInGrams as Array<any>).map(ShippingFeeTableOrderTotalWeightInGramsDTOToJSON)),
        'isCOD': value.isCOD,
        'codFeeRateCalculationType': value.codFeeRateCalculationType,
        'codFeeTableOrderTotalAmount': ((value.codFeeTableOrderTotalAmount as Array<any>).map(CodFeeTableOrderTotalAmountDTOToJSON)),
        'providerConfig': value.providerConfig,
    };
}

/**
* @export
* @enum {string}
*/
export enum ShippingMethodDraftDTOAuthorityEnum {
    Platform = 'Platform',
    Merchant = 'Merchant'
}
/**
* @export
* @enum {string}
*/
export enum ShippingMethodDraftDTOTypeEnum {
    ShippingServiceProvider = 'ShippingServiceProvider'
}
/**
* @export
* @enum {string}
*/
export enum ShippingMethodDraftDTOProviderTypeEnum {
    Speedy = 'Speedy',
    Econt = 'Econt',
    Custom = 'Custom'
}
/**
* @export
* @enum {string}
*/
export enum ShippingMethodDraftDTOShippingFeeRateCalculationTypeEnum {
    OrderTotalWeightInGrams = 'OrderTotalWeightInGrams'
}
/**
* @export
* @enum {string}
*/
export enum ShippingMethodDraftDTOCodFeeRateCalculationTypeEnum {
    OrderTotalAmount = 'OrderTotalAmount'
}


