/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AddressDTO,
    AddressDTOFromJSON,
    AddressDTOFromJSONTyped,
    AddressDTOToJSON,
    ShippingDeliveryItemDTO,
    ShippingDeliveryItemDTOFromJSON,
    ShippingDeliveryItemDTOFromJSONTyped,
    ShippingDeliveryItemDTOToJSON,
    ShippingDeliveryParcelDTO,
    ShippingDeliveryParcelDTOFromJSON,
    ShippingDeliveryParcelDTOFromJSONTyped,
    ShippingDeliveryParcelDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface ShippingDeliveryDTO
 */
export interface ShippingDeliveryDTO {
    /**
     * 
     * @type {number}
     * @memberof ShippingDeliveryDTO
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof ShippingDeliveryDTO
     */
    updatedAt: number;
    /**
     * 
     * @type {string}
     * @memberof ShippingDeliveryDTO
     */
    id: string;
    /**
     * 
     * @type {Array<ShippingDeliveryParcelDTO>}
     * @memberof ShippingDeliveryDTO
     */
    parcels?: Array<ShippingDeliveryParcelDTO>;
    /**
     * 
     * @type {string}
     * @memberof ShippingDeliveryDTO
     */
    status: ShippingDeliveryDTOStatusEnum;
    /**
     * 
     * @type {AddressDTO}
     * @memberof ShippingDeliveryDTO
     */
    address: AddressDTO;
    /**
     * 
     * @type {Array<ShippingDeliveryItemDTO>}
     * @memberof ShippingDeliveryDTO
     */
    items: Array<ShippingDeliveryItemDTO>;
}

export function ShippingDeliveryDTOFromJSON(json: any): ShippingDeliveryDTO {
    return ShippingDeliveryDTOFromJSONTyped(json, false);
}

export function ShippingDeliveryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingDeliveryDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'id': json['id'],
        'parcels': !exists(json, 'parcels') ? undefined : ((json['parcels'] as Array<any>).map(ShippingDeliveryParcelDTOFromJSON)),
        'status': json['status'],
        'address': AddressDTOFromJSON(json['address']),
        'items': ((json['items'] as Array<any>).map(ShippingDeliveryItemDTOFromJSON)),
    };
}

export function ShippingDeliveryDTOToJSON(value?: ShippingDeliveryDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'id': value.id,
        'parcels': value.parcels === undefined ? undefined : ((value.parcels as Array<any>).map(ShippingDeliveryParcelDTOToJSON)),
        'status': value.status,
        'address': AddressDTOToJSON(value.address),
        'items': ((value.items as Array<any>).map(ShippingDeliveryItemDTOToJSON)),
    };
}

/**
* @export
* @enum {string}
*/
export enum ShippingDeliveryDTOStatusEnum {
    Initial = 'Initial',
    Pending = 'Pending',
    Delayed = 'Delayed',
    Partial = 'Partial',
    Shipped = 'Shipped',
    BackOrder = 'BackOrder'
}


