/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShippingDeliveryItemDTO
 */
export interface ShippingDeliveryItemDTO {
    /**
     * 
     * @type {string}
     * @memberof ShippingDeliveryItemDTO
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof ShippingDeliveryItemDTO
     */
    quantity: number;
}

export function ShippingDeliveryItemDTOFromJSON(json: any): ShippingDeliveryItemDTO {
    return ShippingDeliveryItemDTOFromJSONTyped(json, false);
}

export function ShippingDeliveryItemDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingDeliveryItemDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'quantity': json['quantity'],
    };
}

export function ShippingDeliveryItemDTOToJSON(value?: ShippingDeliveryItemDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'quantity': value.quantity,
    };
}


