/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShippingParcelTrackingDataDTO
 */
export interface ShippingParcelTrackingDataDTO {
    /**
     * 
     * @type {string}
     * @memberof ShippingParcelTrackingDataDTO
     */
    checkId?: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingParcelTrackingDataDTO
     */
    trackingId?: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingParcelTrackingDataDTO
     */
    carrier?: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingParcelTrackingDataDTO
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof ShippingParcelTrackingDataDTO
     */
    providerTransaction?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ShippingParcelTrackingDataDTO
     */
    isReturn?: boolean;
}

export function ShippingParcelTrackingDataDTOFromJSON(json: any): ShippingParcelTrackingDataDTO {
    return ShippingParcelTrackingDataDTOFromJSONTyped(json, false);
}

export function ShippingParcelTrackingDataDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingParcelTrackingDataDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checkId': !exists(json, 'checkId') ? undefined : json['checkId'],
        'trackingId': !exists(json, 'trackingId') ? undefined : json['trackingId'],
        'carrier': !exists(json, 'carrier') ? undefined : json['carrier'],
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
        'providerTransaction': !exists(json, 'providerTransaction') ? undefined : json['providerTransaction'],
        'isReturn': !exists(json, 'isReturn') ? undefined : json['isReturn'],
    };
}

export function ShippingParcelTrackingDataDTOToJSON(value?: ShippingParcelTrackingDataDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checkId': value.checkId,
        'trackingId': value.trackingId,
        'carrier': value.carrier,
        'provider': value.provider,
        'providerTransaction': value.providerTransaction,
        'isReturn': value.isReturn,
    };
}


