/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    KeyReferenceDTO,
    KeyReferenceDTOFromJSON,
    KeyReferenceDTOFromJSONTyped,
    KeyReferenceDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface StateDraftDTO
 */
export interface StateDraftDTO {
    /**
     * 
     * @type {number}
     * @memberof StateDraftDTO
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof StateDraftDTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof StateDraftDTO
     */
    type: StateDraftDTOTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof StateDraftDTO
     */
    name?: object;
    /**
     * 
     * @type {object}
     * @memberof StateDraftDTO
     */
    description?: object;
    /**
     * 
     * @type {string}
     * @memberof StateDraftDTO
     */
    color?: string;
    /**
     * 
     * @type {boolean}
     * @memberof StateDraftDTO
     */
    initial: boolean;
    /**
     * 
     * @type {Array<KeyReferenceDTO>}
     * @memberof StateDraftDTO
     */
    transitions: Array<KeyReferenceDTO>;
}

export function StateDraftDTOFromJSON(json: any): StateDraftDTO {
    return StateDraftDTOFromJSONTyped(json, false);
}

export function StateDraftDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateDraftDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'key': json['key'],
        'type': json['type'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'initial': json['initial'],
        'transitions': ((json['transitions'] as Array<any>).map(KeyReferenceDTOFromJSON)),
    };
}

export function StateDraftDTOToJSON(value?: StateDraftDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'key': value.key,
        'type': value.type,
        'name': value.name,
        'description': value.description,
        'color': value.color,
        'initial': value.initial,
        'transitions': ((value.transitions as Array<any>).map(KeyReferenceDTOToJSON)),
    };
}

/**
* @export
* @enum {string}
*/
export enum StateDraftDTOTypeEnum {
    OrderState = 'OrderState',
    LineItemState = 'LineItemState',
    PaymentState = 'PaymentState',
    WalletState = 'WalletState'
}


