/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreViewDTO
 */
export interface StoreViewDTO {
    /**
     * 
     * @type {number}
     * @memberof StoreViewDTO
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof StoreViewDTO
     */
    storeKey: string;
    /**
     * 
     * @type {string}
     * @memberof StoreViewDTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof StoreViewDTO
     */
    languageCode: string;
    /**
     * 
     * @type {string}
     * @memberof StoreViewDTO
     */
    themeKey: string;
    /**
     * 
     * @type {string}
     * @memberof StoreViewDTO
     */
    themeVersion: string;
    /**
     * 
     * @type {object}
     * @memberof StoreViewDTO
     */
    themeConfig: object;
    /**
     * 
     * @type {object}
     * @memberof StoreViewDTO
     */
    themeConfigSchema: object;
    /**
     * 
     * @type {string}
     * @memberof StoreViewDTO
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof StoreViewDTO
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof StoreViewDTO
     */
    updatedAt: number;
}

export function StoreViewDTOFromJSON(json: any): StoreViewDTO {
    return StoreViewDTOFromJSONTyped(json, false);
}

export function StoreViewDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreViewDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'storeKey': json['storeKey'],
        'key': json['key'],
        'languageCode': json['languageCode'],
        'themeKey': json['themeKey'],
        'themeVersion': json['themeVersion'],
        'themeConfig': json['themeConfig'],
        'themeConfigSchema': json['themeConfigSchema'],
        'id': json['_id'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function StoreViewDTOToJSON(value?: StoreViewDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'storeKey': value.storeKey,
        'key': value.key,
        'languageCode': value.languageCode,
        'themeKey': value.themeKey,
        'themeVersion': value.themeVersion,
        'themeConfig': value.themeConfig,
        'themeConfigSchema': value.themeConfigSchema,
        '_id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
    };
}


