/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreDraftDTO
 */
export interface StoreDraftDTO {
    /**
     * 
     * @type {number}
     * @memberof StoreDraftDTO
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof StoreDraftDTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof StoreDraftDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof StoreDraftDTO
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StoreDraftDTO
     */
    tags?: Array<string>;
}

export function StoreDraftDTOFromJSON(json: any): StoreDraftDTO {
    return StoreDraftDTOFromJSONTyped(json, false);
}

export function StoreDraftDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreDraftDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'key': json['key'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}

export function StoreDraftDTOToJSON(value?: StoreDraftDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'key': value.key,
        'name': value.name,
        'description': value.description,
        'tags': value.tags,
    };
}


