/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubRateDTO
 */
export interface SubRateDTO {
    /**
     * 
     * @type {string}
     * @memberof SubRateDTO
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof SubRateDTO
     */
    amount: number;
}

export function SubRateDTOFromJSON(json: any): SubRateDTO {
    return SubRateDTOFromJSONTyped(json, false);
}

export function SubRateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubRateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'amount': json['amount'],
    };
}

export function SubRateDTOToJSON(value?: SubRateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'amount': value.amount,
    };
}


