/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TaxRateDTO,
    TaxRateDTOFromJSON,
    TaxRateDTOFromJSONTyped,
    TaxRateDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface TaxCategoryDTO
 */
export interface TaxCategoryDTO {
    /**
     * 
     * @type {number}
     * @memberof TaxCategoryDTO
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof TaxCategoryDTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof TaxCategoryDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TaxCategoryDTO
     */
    description?: string;
    /**
     * 
     * @type {Array<TaxRateDTO>}
     * @memberof TaxCategoryDTO
     */
    rates: Array<TaxRateDTO>;
    /**
     * 
     * @type {string}
     * @memberof TaxCategoryDTO
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof TaxCategoryDTO
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof TaxCategoryDTO
     */
    updatedAt: number;
}

export function TaxCategoryDTOFromJSON(json: any): TaxCategoryDTO {
    return TaxCategoryDTOFromJSONTyped(json, false);
}

export function TaxCategoryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxCategoryDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'key': json['key'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'rates': ((json['rates'] as Array<any>).map(TaxRateDTOFromJSON)),
        'id': json['id'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function TaxCategoryDTOToJSON(value?: TaxCategoryDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'key': value.key,
        'name': value.name,
        'description': value.description,
        'rates': ((value.rates as Array<any>).map(TaxRateDTOToJSON)),
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
    };
}


