/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TaxRateDTO,
    TaxRateDTOFromJSON,
    TaxRateDTOFromJSONTyped,
    TaxRateDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface TaxCategoryDraftDTO
 */
export interface TaxCategoryDraftDTO {
    /**
     * 
     * @type {number}
     * @memberof TaxCategoryDraftDTO
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof TaxCategoryDraftDTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof TaxCategoryDraftDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TaxCategoryDraftDTO
     */
    description?: string;
    /**
     * 
     * @type {Array<TaxRateDTO>}
     * @memberof TaxCategoryDraftDTO
     */
    rates: Array<TaxRateDTO>;
}

export function TaxCategoryDraftDTOFromJSON(json: any): TaxCategoryDraftDTO {
    return TaxCategoryDraftDTOFromJSONTyped(json, false);
}

export function TaxCategoryDraftDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxCategoryDraftDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'key': json['key'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'rates': ((json['rates'] as Array<any>).map(TaxRateDTOFromJSON)),
    };
}

export function TaxCategoryDraftDTOToJSON(value?: TaxCategoryDraftDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'key': value.key,
        'name': value.name,
        'description': value.description,
        'rates': ((value.rates as Array<any>).map(TaxRateDTOToJSON)),
    };
}


