/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MoneyDTO,
    MoneyDTOFromJSON,
    MoneyDTOFromJSONTyped,
    MoneyDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface TaxedItemPriceDTO
 */
export interface TaxedItemPriceDTO {
    /**
     * 
     * @type {MoneyDTO}
     * @memberof TaxedItemPriceDTO
     */
    totalNet: MoneyDTO;
    /**
     * 
     * @type {MoneyDTO}
     * @memberof TaxedItemPriceDTO
     */
    totalGross: MoneyDTO;
}

export function TaxedItemPriceDTOFromJSON(json: any): TaxedItemPriceDTO {
    return TaxedItemPriceDTOFromJSONTyped(json, false);
}

export function TaxedItemPriceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxedItemPriceDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalNet': MoneyDTOFromJSON(json['totalNet']),
        'totalGross': MoneyDTOFromJSON(json['totalGross']),
    };
}

export function TaxedItemPriceDTOToJSON(value?: TaxedItemPriceDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalNet': MoneyDTOToJSON(value.totalNet),
        'totalGross': MoneyDTOToJSON(value.totalGross),
    };
}


