/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileUpdateDTO
 */
export interface UserProfileUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateDTO
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateDTO
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateDTO
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateDTO
     */
    email: string;
}

export function UserProfileUpdateDTOFromJSON(json: any): UserProfileUpdateDTO {
    return UserProfileUpdateDTOFromJSONTyped(json, false);
}

export function UserProfileUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'middleName': !exists(json, 'middleName') ? undefined : json['middleName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'email': json['email'],
    };
}

export function UserProfileUpdateDTOToJSON(value?: UserProfileUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'middleName': value.middleName,
        'lastName': value.lastName,
        'email': value.email,
    };
}


