/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateDTO
 */
export interface UserUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDTO
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDTO
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDTO
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateDTO
     */
    role: string;
}

export function UserUpdateDTOFromJSON(json: any): UserUpdateDTO {
    return UserUpdateDTOFromJSONTyped(json, false);
}

export function UserUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'middleName': !exists(json, 'middleName') ? undefined : json['middleName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'email': json['email'],
        'role': json['role'],
    };
}

export function UserUpdateDTOToJSON(value?: UserUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'middleName': value.middleName,
        'lastName': value.lastName,
        'email': value.email,
        'role': value.role,
    };
}


