/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IdReferenceDTO,
    IdReferenceDTOFromJSON,
    IdReferenceDTOFromJSONTyped,
    IdReferenceDTOToJSON,
    KeyReferenceDTO,
    KeyReferenceDTOFromJSON,
    KeyReferenceDTOFromJSONTyped,
    KeyReferenceDTOToJSON,
    MoneyDTO,
    MoneyDTOFromJSON,
    MoneyDTOFromJSONTyped,
    MoneyDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface WalletDTO
 */
export interface WalletDTO {
    /**
     * 
     * @type {string}
     * @memberof WalletDTO
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof WalletDTO
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof WalletDTO
     */
    updatedAt: number;
    /**
     * 
     * @type {Array<IdReferenceDTO>}
     * @memberof WalletDTO
     */
    owners: Array<IdReferenceDTO>;
    /**
     * 
     * @type {number}
     * @memberof WalletDTO
     */
    version?: number;
    /**
     * 
     * @type {KeyReferenceDTO}
     * @memberof WalletDTO
     */
    type: KeyReferenceDTO;
    /**
     * 
     * @type {string}
     * @memberof WalletDTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof WalletDTO
     */
    status: WalletDTOStatusEnum;
    /**
     * 
     * @type {MoneyDTO}
     * @memberof WalletDTO
     */
    availableAmount?: MoneyDTO;
    /**
     * 
     * @type {MoneyDTO}
     * @memberof WalletDTO
     */
    lastKnownAvailableAmount?: MoneyDTO;
    /**
     * 
     * @type {number}
     * @memberof WalletDTO
     */
    lastSyncAt?: number;
    /**
     * 
     * @type {object}
     * @memberof WalletDTO
     */
    custom?: object;
}

export function WalletDTOFromJSON(json: any): WalletDTO {
    return WalletDTOFromJSONTyped(json, false);
}

export function WalletDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'owners': ((json['owners'] as Array<any>).map(IdReferenceDTOFromJSON)),
        'version': !exists(json, 'version') ? undefined : json['version'],
        'type': KeyReferenceDTOFromJSON(json['type']),
        'key': json['key'],
        'status': json['status'],
        'availableAmount': !exists(json, 'availableAmount') ? undefined : MoneyDTOFromJSON(json['availableAmount']),
        'lastKnownAvailableAmount': !exists(json, 'lastKnownAvailableAmount') ? undefined : MoneyDTOFromJSON(json['lastKnownAvailableAmount']),
        'lastSyncAt': !exists(json, 'lastSyncAt') ? undefined : json['lastSyncAt'],
        'custom': !exists(json, 'custom') ? undefined : json['custom'],
    };
}

export function WalletDTOToJSON(value?: WalletDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'owners': ((value.owners as Array<any>).map(IdReferenceDTOToJSON)),
        'version': value.version,
        'type': KeyReferenceDTOToJSON(value.type),
        'key': value.key,
        'status': value.status,
        'availableAmount': MoneyDTOToJSON(value.availableAmount),
        'lastKnownAvailableAmount': MoneyDTOToJSON(value.lastKnownAvailableAmount),
        'lastSyncAt': value.lastSyncAt,
        'custom': value.custom,
    };
}

/**
* @export
* @enum {string}
*/
export enum WalletDTOStatusEnum {
    Requested = 'requested',
    Inactive = 'inactive',
    Active = 'active',
    Locked = 'locked',
    Cancelled = 'cancelled',
    Lost = 'lost',
    Stolen = 'stolen',
    Suspended = 'suspended'
}


