/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    KeyReferenceDTO,
    KeyReferenceDTOFromJSON,
    KeyReferenceDTOFromJSONTyped,
    KeyReferenceDTOToJSON,
    ProductDTO,
    ProductDTOFromJSON,
    ProductDTOFromJSONTyped,
    ProductDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface WishListDTO
 */
export interface WishListDTO {
    /**
     * 
     * @type {string}
     * @memberof WishListDTO
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof WishListDTO
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof WishListDTO
     */
    updatedAt: number;
    /**
     * 
     * @type {KeyReferenceDTO}
     * @memberof WishListDTO
     */
    priceList: KeyReferenceDTO;
    /**
     * 
     * @type {KeyReferenceDTO}
     * @memberof WishListDTO
     */
    store: KeyReferenceDTO;
    /**
     * 
     * @type {string}
     * @memberof WishListDTO
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof WishListDTO
     */
    anonymousId?: string;
    /**
     * 
     * @type {Array<ProductDTO>}
     * @memberof WishListDTO
     */
    products: Array<ProductDTO>;
}

export function WishListDTOFromJSON(json: any): WishListDTO {
    return WishListDTOFromJSONTyped(json, false);
}

export function WishListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): WishListDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'priceList': KeyReferenceDTOFromJSON(json['priceList']),
        'store': KeyReferenceDTOFromJSON(json['store']),
        'customerId': !exists(json, 'customerId') ? undefined : json['customerId'],
        'anonymousId': !exists(json, 'anonymousId') ? undefined : json['anonymousId'],
        'products': ((json['products'] as Array<any>).map(ProductDTOFromJSON)),
    };
}

export function WishListDTOToJSON(value?: WishListDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'priceList': KeyReferenceDTOToJSON(value.priceList),
        'store': KeyReferenceDTOToJSON(value.store),
        'customerId': value.customerId,
        'anonymousId': value.anonymousId,
        'products': ((value.products as Array<any>).map(ProductDTOToJSON)),
    };
}


