/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * Auth API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    KeyReferenceDTO,
    KeyReferenceDTOFromJSON,
    KeyReferenceDTOFromJSONTyped,
    KeyReferenceDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface WishListDraftDTO
 */
export interface WishListDraftDTO {
    /**
     * 
     * @type {KeyReferenceDTO}
     * @memberof WishListDraftDTO
     */
    priceList: KeyReferenceDTO;
    /**
     * 
     * @type {KeyReferenceDTO}
     * @memberof WishListDraftDTO
     */
    store: KeyReferenceDTO;
    /**
     * 
     * @type {string}
     * @memberof WishListDraftDTO
     */
    customerId?: string;
    /**
     * 
     * @type {string}
     * @memberof WishListDraftDTO
     */
    anonymousId?: string;
}

export function WishListDraftDTOFromJSON(json: any): WishListDraftDTO {
    return WishListDraftDTOFromJSONTyped(json, false);
}

export function WishListDraftDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): WishListDraftDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'priceList': KeyReferenceDTOFromJSON(json['priceList']),
        'store': KeyReferenceDTOFromJSON(json['store']),
        'customerId': !exists(json, 'customerId') ? undefined : json['customerId'],
        'anonymousId': !exists(json, 'anonymousId') ? undefined : json['anonymousId'],
    };
}

export function WishListDraftDTOToJSON(value?: WishListDraftDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'priceList': KeyReferenceDTOToJSON(value.priceList),
        'store': KeyReferenceDTOToJSON(value.store),
        'customerId': value.customerId,
        'anonymousId': value.anonymousId,
    };
}


